# Generated by Django 3.2.8 on 2021-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('pasaporte', models.CharField(max_length=100, verbose_name='Pasaporte')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('nick', models.CharField(max_length=10, verbose_name='Nick')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('seniority', models.CharField(choices=[('1', 'Junior'), ('2', 'Semi-Senior'), ('3', 'Senior')], max_length=20, verbose_name='Seniority')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'abstract': False,
                'unique_together': {('pais', 'nick')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('pasaporte', models.CharField(max_length=100, verbose_name='Pasaporte')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('nick', models.CharField(max_length=10, verbose_name='Nick')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'abstract': False,
                'unique_together': {('pais', 'nick')},
            },
        ),
    ]
