# Generated by Django 3.2.8 on 2021-10-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='macionalidad',
            new_name='nacionalidad',
        ),
    ]
