# Generated by Django 3.2.8 on 2021-10-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_rename_macionalidad_lector_nacionalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
